### ISSUE TITLE
Projects with no teams cannot be loaded

### ISSUE THREAD

**Issue by Anarchid** [Spring-SpringBoard/SpringBoard-Core#293] opened 2018-01-05 23:30 UTC
I'm using SBC to edit a map, and when i save the project and then load it, i get this:
```
[f=-000001] Error: [ExitSpringProcess] errorMsg="missing AI.Team in GameSetup script" msgCaption="Spring: caught content_error: " mainThread=1
[f=-000001] Error: [Watchdog::ClearTimer(id)] Invalid thread 4 (_threadId=(nil))
```
Followed by what looks like CTD (though really it's intentional quit on Spring's part)

**Comment by gajop** [comment] 2018-01-06 04:53
duplicate of https://github.com/Spring-SpringBoard/SpringBoard-Core/issues/280

Can you please post feedback there? Things just seem to work for me.
Ideally I'd like to see your project files, especially all the .lua and .txt files.
Zipping everything would also help as I could then try to load it myself.

**Closed by gajop** 2018-01-06 04:53 UTC
